title: Benyamin Salimi
description: I'm back-end developer. i like data minig and security
tools: Python | Django | scikit-learn | pentest | linux
note: Smile :)

author: Benyamin salimi
email: benyamin.salimi@gmail.com
timezone: +04:30

url: https://benyamin.pw/
root: /
static: /static

icon: /static/theme/sallar/img/iconn.ico

post_num: all
archive_post_num: all
feed_output: atom.xml

default_floor: fa
default_markup: mmd

disqus_shortname: benyaminsalimi
intensedebate_acct: 909a9ad12566c79462abd680d800cc74

template: sallar

 
 

twitter: https://twitter.com/BenyaminSalimi
github: https://github.com/BenyaminSalimi
linkedin: https://linkedin.com/in/benyaminsalimi/
keybase: https://keybase.io/benyamin/
instagram: https://instagram.com/benyaminsalimi
skype: "skype:benyamin.salimi"
GoogleTrackingID: UA-57633569-3
youtube: https://www.youtube.com/channel/UCakSZE2SPxx9SaGHLzYM7Lg